### ISSUE TITLE
ValueError: Length of values (400) does not match length of index (401)

### ISSUE THREAD

**Issue by furrutiav** [johnny-godoy/bocop-reader#2]
Tengo este error al intentar cargar la solucion al problema jackson_basic de BOCOP en la clase BOCOPSolution. Parece ser que el numero datos en la discretizacion del tiempo es diferente a los valores de alguna de las soluciones.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [87], in <cell line: 1>()
----> 1 a_tf_0_7_tf_5 = BOCOPSolution("sol/1")

File ~\anaconda3\envs\nn\lib\site-packages\bocop_solution.py:58, in BOCOPSolution.__init__(self, working_directory_filename)
     56 controls = [file for file in files if f"stage_{file}" in files]
     57 # Creating bunch objects for each variable type
---> 58 self.adjoint_states = _AdjointStates(self, states)
     59 self.states = _States(self, states)
     60 self.controls = _Controls(self, controls)

File ~\anaconda3\envs\nn\lib\site-packages\internals\_bunches.py:12, in _AdjointStates.__init__(self, solution, variable_list)
     11 def __init__(self, solution: BOCOPSolution, variable_list: list[str]):
---> 12     super().__init__(solution, [f"{variable}_adjoint_state" for variable in variable_list])

File ~\anaconda3\envs\nn\lib\site-packages\internals\_variable_bunch.py:31, in _VariableBunch.__init__(self, solution, variable_list)
     23 def __init__(self, solution: BOCOPSolution, variable_list: list[str]):
     24     """
     25     Parameters
     26     ----------
   (...)
     29     variable_list: list[str]
     30         A list with each variable named."""
---> 31     self.variables = {name: _Variable(solution, name) for name in variable_list}
     32     self.working_directory_filename = solution.working_directory_filename
     33     self.dataframe = pd.DataFrame({name: variable.series
     34                                    for name, variable in self.variables.items()})

File ~\anaconda3\envs\nn\lib\site-packages\internals\_variable_bunch.py:31, in <dictcomp>(.0)
     23 def __init__(self, solution: BOCOPSolution, variable_list: list[str]):
     24     """
     25     Parameters
     26     ----------
   (...)
     29     variable_list: list[str]
     30         A list with each variable named."""
---> 31     self.variables = {name: _Variable(solution, name) for name in variable_list}
     32     self.working_directory_filename = solution.working_directory_filename
     33     self.dataframe = pd.DataFrame({name: variable.series
     34                                    for name, variable in self.variables.items()})

File ~\anaconda3\envs\nn\lib\site-packages\internals\_variable.py:46, in _Variable.__init__(self, solution, name)
     44 times = solution.stage_times if len(solution.stage_times) == len(self.values) else solution.discretization_times
     45 self.discretization_times = times
---> 46 self.series = pd.Series(self.values, index=self.discretization_times, name=name)
     47 # Creating the interpolator object
     48 self.cubic_interpolator = scipy.interpolate.InterpolatedUnivariateSpline(self.discretization_times, self.values)

File ~\anaconda3\envs\nn\lib\site-packages\pandas\core\series.py:442, in Series.__init__(self, data, index, dtype, name, copy, fastpath)
    440     index = default_index(len(data))
    441 elif is_list_like(data):
--> 442     com.require_length_match(data, index)
    444 # create/copy the manager
    445 if isinstance(data, (SingleBlockManager, SingleArrayManager)):

File ~\anaconda3\envs\nn\lib\site-packages\pandas\core\common.py:557, in require_length_match(data, index)
    553 """
    554 Check the length of data matches the length of the index.
    555 """
    556 if len(data) != len(index):
--> 557     raise ValueError(
    558         "Length of values "
    559         f"({len(data)}) "
    560         "does not match length of index "
    561         f"({len(index)})"
    562     )

ValueError: Length of values (400) does not match length of index (401)

**Comment by johnny-godoy** [comment]
Muchísimas gracias por el Issue.

En `dev` dejé un fix que debería solucionar este problema, fui nuclear y quité las variables adjuntas por ahora (que dudo que utilices ahora, y debo investigar mejor respecto a su tiempo de discretización dado que no tiene archivo asociado)

Para instalarlo usa

`pip install git+https://github.com/johnny-godoy/bocop-reader.git@dev`

Y me cuentas que tal por favor :)

**Comment by furrutiav** [comment]
Hice lo que mencionas pero el error se mantiene.

**Comment by johnny-godoy** [comment]
Intenta primero desisntalar con `pip uninstall bocop-solution` y luego resinstalar.

**Comment by johnny-godoy** [comment]
Si eso no funciona, necesitaría el nuevo mensaje de error (sí es exactamente el mismo, significa que tu instalación no tiene el branch correcto), e indica si cambiaste los parámetros de `jackson_basic`, porque no puedo replicar el problema en Colab.

**Comment by furrutiav** [comment]
Me sale mismo error, aqui te dejo las soluciones que exporte desde BOCOP https://github.com/furrutiav/MA4703/tree/lab1/lab1/ex6/a_tf_0_7_tf_5

**Comment by johnny-godoy** [comment]
Me funcionó todo perfecto con esos archivos. Ve lo que imprime el siguiente comando:

`pip freeze | grep bocop-solution`

El resultado debería ser algo como `bocop-solution @ git+https://github.com/johnny-godoy/bocop-reader.git@XXXXX`


Si XXXXX = b2f9b5434091555ca2a1494221ef0dbb9c7ab218 estás todavía con las instalación del branch `main`, y en este caso me falla. Pero con XXXXX = abbb8f4b2d21fc270538998e3641dd940a507c97 quedo en `dev` y funciona.

**Comment by johnny-godoy** [comment]
Si lo estás probando de un Jupyter Notebook podría servir reiniciar el kernel después de desintalar/reinstalar

**Comment by furrutiav** [comment]
Genial! Todo resuelto.
